server:
  port: 8084

spring:
  application:
    name: PayeeService

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orclpdb
    driver-class-name: oracle.jdbc.OracleDriver
    username: Satyajit
    password: 5275

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    com.oracle.payeeservice.service.MailClient: DEBUG
    org.springframework.cloud.openfeign: DEBUG
