# ------------------------------------------------------------------
#          API GATEWAY CONFIGURATION (Fixed)
# ------------------------------------------------------------------
server:
  port: 8080

spring:
  application:
    name: ApiGateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://ADMINSERVICE
          predicates:
            - Path=/admin/**,/admin/account-requests/**,/admin/view/**
        - id: payee-service
          uri: lb://PAYEESERVICE
          predicates:
            - Path=/api/payees/**
        - id: statement-service
          uri: lb://STATEMENTSERVICE
          predicates:
            - Path=/api/statements/**,/api/payees/**
        - id: transaction-service
          uri: lb://TRANSACTIONSERVICE
          predicates:
            - Path=/api/**
        - id: banking-portal
          uri: lb://BANKINGPORTAL
          predicates:
            - Path=/account/**,/accountRequest/**,/customer/**,/mail/**,/otp/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: 
              - "http://localhost:*"
              - "http://127.0.0.1:*"
              - "http://localhost:5500"
              - "http://127.0.0.1:5500"
              - "http://localhost:5502"
              - "http://127.0.0.1:5502"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

# ------------------------------------------------------------------
#          EUREKA CLIENT CONFIGURATION
# ------------------------------------------------------------------
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

# ------------------------------------------------------------------
#          LOGGING (Optional)
# ------------------------------------------------------------------
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

# ------------------------------------------------------------------
#          MANAGEMENT (Optional)
# ------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"